### PR TITLE
Update for latest firmware (work in progress)

### PR DESCRIPTION
**Pull request by tremby**
@algernon I've done my best but have got stuck. Can you help, please?

I hacked at it until it's now building with no warnings. But I have a blank keyboard when I try to activate the effect. What am I doing wrong?

I wondered if it was to do with how ROWS/COLS/map are set, so tried hardcoding those to 4/16 but I still get no lights.

I see that a lot of plugins have an embedded TransientLEDMode class -- do I need one of those?

### CODE REVIEW

**Comment by algernon** [comment]
I _think_ you'll need `TransientLEDMode`, indeed. But at least, the parent should be `LEDMode` instead of `Plugin`. I'll have a look in a bit!

**Comment by algernon** [comment]
Yeah, changing it to use `LEDMode` as its parent makes it work. The animation is super slow though... I seem to recall it being considerably faster.

**Comment by tremby** [comment]
Wow, that's all it was! 🤦

I'll figure out why it's so slow soon. Or do you have any idea? Are LED plugins' `update` methods called less frequently now?

**Comment by algernon** [comment]
They're called every `LEDControl.syncDelay` milliseconds, which is 32 by default. This was done in keyboardio/Kaleidoscope#593, back in March. So yes, `update()` is called _much_ less often now.

If I could make a suggestion, I'd try to transition using a timer for the drop delay instead of counting ticks, because ticks will be heavily dependant on other parts of the sketch. The main loop of a light sketch is considerably faster than one with many resource-hungrier plugins.

**Comment by tremby** [comment]
That sounds like a good idea. I'll look to other plugins to see how
these timers work, or are there docs somewhere?

**Comment by algernon** [comment]
Have a look at the `hasTimerExpired()` method's docs in [kaleidoscope/Runtime.h](https://github.com/keyboardio/Kaleidoscope/blob/5154e93052d2eddc542d367a693a36fb715a6848/src/kaleidoscope/Runtime.h#L94-L119).

**Comment by tremby** [comment]
@algernon, I went with your suggestion and updated how the plugin works.

The configuration has changed a little accordingly.

I've pushed the changeset to master already, but would appreciate if you were to review the changes. I wonder if you can spot any optimizations I can make, for example!

Thanks for your help.

**Comment by algernon** [comment]
The speed looks very nice now, thank you!

There are a number of things I'd change with regards to the plugin, especially if we want to merge it into Kaleidoscope. I'll explain those in #12, feels more fitting there.

**Comment by tremby** [comment]
I look forward to it.

**Pull request merged**
