### PR TITLE
Update example in Readme to current Kaleidoscope practice.

### PR DESCRIPTION
**Pull request by ghoetker**
Updates the README to represent Kaleidoscope's change from "Kaleidoscope.use". Responds to issue #5 .

### CODE REVIEW

**Review by tremby — COMMENTED** [review]
Thanks for this!

I haven't updated my firmware yet...

Is it really correct to run Kaleidoscope.setup() *then* LEDDigitalRainEffect.activate() *then* adjust plugin configuration? The order seems surprising to me.

**Comment by ghoetker** [comment]
Looking at the Example code supplied by Keyboardio, calling Kaleidoscope.setup() seems proper or at least acceptable.  However, it does seem that the configuration should be set before activating the plugin (although it seems to work either way).  I've pushed a new commit that moves the configuration before the activation.

**Comment by tremby** [comment]
Did you mean to close this?

If not, I'll merge it (though I'll tweak the spacing etc a little).

**Comment by ghoetker** [comment]
No, I didn’t mean to close it.  My bad.

Thanks!

Glenn

_______________________________________

Glenn Hoetker
HMSTrust Chair in Social Innovation &
Professor in Business Strategy

Melbourne Business School, University of Melbourne
200 Leicester Street, Carlton, Victoria 3053, Australia<x-apple-data-detectors://1/1>
Email: Glenn.Hoetker@mbs.edu<mailto:Glenn.Hoetker@mbs.edu>
Web:  glennhoetker.com<http://glennhoetker.com/>

[cid:image007.jpg@01D37974.EE7C09F0]



I acknowledge the Traditional Owners of the land on which I work, the Wurundjeri people of the Kulin Nations, and pay my respects to their Elders, past and present.

On 29 Jul 2019, at 2:28 pm, Bart Nagel <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you mean to close this?

If not, I'll merge it (though I'll tweak the spacing etc a little).

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tremby_Kaleidoscope-2DLEDEffect-2DDigitalRain_pull_8-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAPRRICID76MJQS2N2GEA5TQBZWVFA5CNFSM4IHAKJV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD27RPBA-23issuecomment-2D515839876&d=DwMCaQ&c=FcGMiTDX8FO-KAYppnKNhFgYxz2wb40a2pni_SOyB0w&r=echEk7Fq0uKDPVkvqTQ-RBSLNAYmTPw-hKzuELgtdWw&m=wi0gmbXCyjLDQs7q2QljeHszOBKwEFqpwV8XD2EsiwY&s=MRoV9pMOyPuNlPeQMvMwxWld1he-uk1mJxTCZzSIM0Y&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAPRRIDBD57IPCOX4C4DKTTQBZWVFANCNFSM4IHAKJVQ&d=DwMCaQ&c=FcGMiTDX8FO-KAYppnKNhFgYxz2wb40a2pni_SOyB0w&r=echEk7Fq0uKDPVkvqTQ-RBSLNAYmTPw-hKzuELgtdWw&m=wi0gmbXCyjLDQs7q2QljeHszOBKwEFqpwV8XD2EsiwY&s=t3KmKmeArxI1YEbQlz1gWtAxWcaicdnC30jKc5qLDz0&e=>.

----------------------------------------------------------------------
Notice from Melbourne Business School Ltd

The information contained in this e-mail is confidential, and is intended for the named person's use only. It may contain proprietary or legally privileged information. If you have received this email in error, please notify the sender and delete it immediately. You must not, directly or indirectly, use, disclose, distribute, print, or copy any part of this message if you are not the intended recipient.

Internet communications are not secure. You should scan this message and any attachments for viruses. Melbourne Business School does not accept any liability for loss or damage which may result from receipt of this message or any attachments.

**Pull request merged**
